### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by zefexdeveloper** [teovillanueva/dotenv-types#2] opened 2020-08-15 13:51 UTC
I used `npx dotenv-types` it generated the `env.d.ts` on the root but I'm getting:

> Type 'string' is not assignable to type 'number | undefined'.

When trying to assign an environment variable to a config that requires to be a number

```
const options: ConnectionOptions = {
  host: process.env.DATABASE_HOST,
  port: process.env.DATABASE_PORT
}
```

In VSCode it works, it's giving me the IntelliSense but once I run the application using `ts-node-dev` it behaves like it's not there.

How can I solve this? I can't find in the docs any information regarding on how to load the file properly.

**Comment by teovillanueva** [comment] 2020-08-15 18:20
Hi @zefexdeveloper. Thanks for letting me know about this issue. Looks like the property ConnectionOptions expects a number. All generated types by the cli by default are of type string since dotenv parses them as string. A possible solution could be: 

```ts
const options: ConnectionOptions = {
  host: process.env.DATABASE_HOST,
  port: process.env.DATABASE_PORT as number
}
```

or modifying your `.env.d.ts` to make the property DATABASE_PORT of type number instead of the default string type.

Ill start planning some type of parsing for the generated types.

**Comment by calmondev** [comment] 2020-08-15 18:24
I'm having the same problem as him.

@teovillanueva For some reason not even the `as number` is working. I'm getting this error:

> Conversion of type 'string | undefined' to type 'number' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first. Type 'string' is not comparable to type 'number'.ts(2352)

I tried also changing the `.env.d.ts` to number but it still doesn't work, when I run using `ts-node-dev` it gives me an error saying that it requires to be number and not a string (like it's ignoring the `.env.d.ts`).

**Comment by teovillanueva** [comment] 2020-08-15 18:29
Hmm interesting, is your `tsconfig.json` including the definitions file?

**Comment by calmondev** [comment] 2020-08-15 18:31
@teovillanueva Yes, I tried including the definition file but it keeps ignoring. I'm guessing it has something to do with the `ts-node-dev`.
I went looking for some answers and I found this: https://github.com/TypeStrong/ts-node#help-my-types-are-missing

**Comment by teovillanueva** [comment] 2020-08-15 18:58
@calmonr I couldnt replicate that behavior. Could you please show me how your generated types and how you are using them? I created a sample project using these generated types:

```ts
// Generated using https://www.npmjs.com/package/dotenv-types

declare namespace NodeJS {
  export interface ProcessEnv {
    PORT: number;
  }
}
```

and im using it like this:

```ts
type Options = {
    port: number
}

let obj: Options = {
    port: process.env.PORT
}
```
Im using ts-node-dev and it doesnt bring up any errors

**Comment by calmondev** [comment] 2020-08-16 16:38
Here are the steps to reproduce:

`src/index.ts`:

```ts
const { SERVER_PORT } = process.env

type Options = {
  port: number
}

const obj: Options = {
  port: SERVER_PORT
}

console.log(obj)
```

`.env`

```
# server
SERVER_PORT=8080
```

`package.json`:

```json
"scripts": {
  "start:dev": "tsnd -r dotenv/config --respawn src"
},
```

`tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "commonjs",
    "declaration": false,
    "outDir": "build",
    "rootDir": "src",
    "composite": false,
    "removeComments": true,
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "moduleResolution": "node",
    "baseUrl": ".",
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "exclude": ["node_modules", "build"]
}
```

Of course don't forget the `npx dotenv-types` and changing `SERVER_PORT` from `string` to `number`.

This is the error I'm getting:

> error TS2322: Type 'string | undefined' is not assignable to type 'number'. Type 'undefined' is not assignable to type 'number'.

**Comment by tomascenteno42** [comment] 2020-08-16 17:23
@calmonr Hi, this is a known error with `ts-node` [not being able to pickup types](https://github.com/TypeStrong/ts-node#help-my-types-are-missing). A simple solution to get it working with `ts-node` and `ts-node-dev` its to add `/// <reference path="../env.d.ts" />` at the top of your `src/index.ts`.

**Comment by teovillanueva** [comment] 2020-08-16 17:41
I can confirm that @tomascenteno42 solution works with `ts-node-dev`. Clearly it isnt the best solution but i couldnt get it to work in another way.

**Comment by calmondev** [comment] 2020-08-16 21:05
It's the best approach so far, thank you guys @teovillanueva @tomascenteno42. It's not a problem with the tool itself so I think that you can close the issue if @zefexdeveloper is ok with that and put in the docs that when using `ts-node` or `ts-node-dev` it's required to have triple-slash directive as a relative path within your project.

**Comment by theprobugmaker** [comment] 2020-08-17 06:25
Sorry for the delay answering. Thank you guys. The @tomascenteno42 solution worked like a charm.

I think it's fine to close the issue as @calmonr mentioned.

**Closed by theprobugmaker** 2020-08-17 06:25 UTC
